Feat/wit 222 event card
unswwit/website pull request #100
Opened 2024-11-09 15:48 UTC by Yukiboki

Linear: https://linear.app/unswwit/issue/WIT-222/what-weve-been-up-to-component-ui-only

I've added the card section and replaced the innovative slide section. 
Also I've added the pages that the buttons lead to. 
I've tried to make it so that the when the pictures update, they actually are of an appropriate size the the image container while still maintaining its proportion.

2024-11-10 16:31 UTC, ItsLame requested changes

2024-11-10 16:31 UTC, ItsLame commented on styles/HomeEventsCard.module.css
make sure to have consistent indentations

2024-11-15 01:37 UTC, ItsLame requested changes

2024-11-15 01:37 UTC, ItsLame commented on styles/HomeEventsCard.module.css
> +.card-button:hover {
line 83 - Ensure consistent casing for class names. In this case it's camelCase

2024-11-15 01:37 UTC, ItsLame commented on styles/HomeEventsCard.module.css
> +.card-button:hover {
Also, is this used anywhere?

2024-11-15 05:19 UTC, Yukiboki commented on styles/HomeEventsCard.module.css
> +.card-button:hover {
yesyes i've just fixed it in the recent commits tysm

2024-11-15 05:20 UTC, Yukiboki commented on styles/HomeEventsCard.module.css
not sure if you can still see the picture of my screenshot but the indentations look good on my vs code hmm maybe its github? Same thing happened when i did 1531

2024-11-15 10:50 UTC, ItsLame commented on styles/HomeEventsCard.module.css
Ohh i think it's because you used tab instead of spaces. There's a setting for it in vscode. It's generally better to use spaces imo because tab size can vary.

2024-11-15 10:51 UTC, ItsLame commented on styles/HomeEventsCard.module.css
I've fixed the weird spacing displayed on github by converting all tabs to spaces in the code.

2024-11-15 11:06 UTC, ItsLame approved these changes

2024-11-15 12:07 UTC, merged