Update/our story timeline
unswwit/website pull request #209
Opened 2022-05-14 19:22 UTC by Eddyyyh

Merge updated timeline from our story into master branch.

2022-05-19 09:29 UTC, joanna209 requested changes

2022-05-19 09:29 UTC, joanna209 commented on src/components/Timeline.js
> +        defaultValue={page === "teams" || page === "events" ? 100 : 250}
Avoid using ternary syntax here and in general, looks more confusing than what we had originally

2022-05-19 09:29 UTC, joanna209 commented on src/components/Timeline.js
> +          // page === "teams" ? styles.teams : page === "events" ? styles.events : styles.marketingArchive
Delete comment

2022-05-19 09:29 UTC, joanna209 commented on src/ourStory/OurStoryTimeline.js
> +        margin={"3%"}
Remove inline style

2022-05-19 09:29 UTC, joanna209 commented on src/ourStory/OurStoryTimeline.module.css
> +  box-shadow: 7px 7px 8px #c4c4c4;
Tone down the box shadow - make it similar to the opportunities page cards for consistency. Remove border as well

2022-05-19 09:29 UTC, joanna209 commented on src/ourStory/OurStoryTimeline.module.css
> +li {
Clean up variable names as well eg ul, li - it is not clear as to what the purpose of these variables are. Avoid using margin and opt for padding instead - better for responsiveness

2022-05-19 09:29 UTC, joanna209 commented on src/ourStory/OurStoryTimeline.js
> +              src=
Refactor this into an object that stores the images by year and pass it in through here instead of ternary syntax - looks a lot cleaner and less confusing. See partnerships data in sponsors page for reference

2022-05-27 15:10 UTC, Eddyyyh commented on src/components/Timeline.js
> +          // page === "teams" ? styles.teams : page === "events" ? styles.events : styles.marketingArchive
removed comment!

2022-05-27 15:11 UTC, Eddyyyh commented on src/ourStory/OurStoryTimeline.js
> +              src=
fixed!

2022-05-27 15:11 UTC, Eddyyyh commented on src/ourStory/OurStoryTimeline.module.css
> +  box-shadow: 7px 7px 8px #c4c4c4;
Done!

2022-05-27 15:11 UTC, Eddyyyh commented on src/ourStory/OurStoryTimeline.module.css
> +li {
done!

2022-05-28 08:00 UTC, joanna209 approved these changes

2022-05-28 08:01 UTC, merged