feat: recaptcha for contact us form
unswwit/website pull request #212
Opened 2022-05-16 10:03 UTC by mrzpn

2022-05-16 10:12 UTC, mrzpn commented
wait sorry - just realised I hardcoded something while testing. will fix that first

2022-05-21 10:19 UTC, joanna209 requested changes

2022-05-21 10:19 UTC, joanna209 commented on src/contact/contactForm.js
> +          size="invisible"
Switch recaptcha mode from "invisible" to "I am not a robot". The latter is more secure as it provides users with an extra challenge (usually in the form of identifying X object in a set of pictures)

2022-05-21 10:19 UTC, joanna209 commented on src/contact/contactForm.js
> +    try {
Avoid using try/catch syntax and instead opt for .then()/.catch() syntax

2022-05-22 10:08 UTC, joanna209 requested changes

2022-05-22 10:08 UTC, joanna209 commented on src/contact/contactForm.js
> +      return false;
Console log the error here, with console.error(error). It's hard to tell what happened if we only return false here

2022-05-23 09:58 UTC, mrzpn commented on src/contact/contactForm.js
> +    try {
I've tried implementing it this way, but I couldn't get it working. I need the async/await method to perform the captcha verification and I don't believe this works with .then() syntax (unless I'm missing something?)

2022-05-26 21:42 UTC, joanna209 commented on src/contact/contactForm.js
> +    try {
Ah that's alright - thanks for trying it out anyways

2022-06-05 11:23 UTC, joanna209 approved these changes

2022-06-05 11:24 UTC, merged